global using Ardalis.SharedKernel;
global using Ardalis.Specification.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using CinemaService.Core.Entities;
global using CinemaService.Core.Interfaces;
global using CinemaService.Infrastructure.Data;
